paths:
  /hardware:
    get:
      operationId: mntnr_hardware.api_v1.logic.say_hello
      summary: says hello
      tags: ['hardware']
      responses:
        default:
          description: success

  /hardware/datacenters:
    get:
      operationId: mntnr_hardware.api_v1.logic.datacenters_list
      summary: lists datacenters
      tags: ['hardware']
      responses:
        200:
          description: list of datacenters
          schema:
            $ref: '#/definitions/DatacenterList'
    post:
      operationId: mntnr_hardware.api_v1.logic.datacenter_create
      summary: creates a datacenter
      tags: ['hardware']
      parameters:
        - name: datacenter
          in: body
          description: the datacenter object to create
          schema:
            $ref: '#/definitions/Datacenter'
      responses:
        201:
          description: created datacenter
          schema:
            $ref: '#/definitions/Datacenter'

  /hardware/datacenters/{id}:
    get:
      operationId: mntnr_hardware.api_v1.logic.datacenter_detail
      summary: shows datacenter details
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the datacenter
      responses:
        200:
          description: datacenter details
          schema:
            $ref: '#/definitions/Datacenter'
    delete:
      operationId: mntnr_hardware.api_v1.logic.datacenter_delete
      summary: deletes datacenter
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the datacenter
      responses:
        default:
          description: success
    put:
      operationId: mntnr_hardware.api_v1.logic.datacenter_update
      summary: updates a datacenter
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the datacenter
        - name: datacenter
          in: body
          description: the datacenter object to create
          schema:
            $ref: '#/definitions/DatacenterUpdate'
      responses:
        200:
          description: datacenter details
          schema:
            $ref: '#/definitions/Datacenter'

  /hardware/cabinets:
    get:
      operationId: mntnr_hardware.api_v1.logic.cabinets_list
      summary: lists cabinets
      tags: ['hardware']
      responses:
        200:
          description: cabinet list
          schema:
            $ref: '#/definitions/CabinetList'
    post:
      operationId: mntnr_hardware.api_v1.logic.cabinet_create
      summary: creates a cabinet
      tags: ['hardware']
      parameters:
        - name: cabinet
          in: body
          description: the cabinet object to create
          schema:
            $ref: '#/definitions/Cabinet'
      responses:
        201:
          description: created cabinet
          schema:
            $ref: '#/definitions/CabinetDetail'

  /hardware/cabinets/{id}:
    get:
      operationId: mntnr_hardware.api_v1.logic.cabinet_detail
      summary: shows details of a cabinet
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the cabinet
      responses:
        200:
          description: cabinet
          schema:
            $ref: '#/definitions/CabinetDetail'
    delete:
      operationId: mntnr_hardware.api_v1.logic.cabinet_delete
      summary: deletes cabinet
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the cabinet
      responses:
        200:
          description: cabinet deleted
    put:
      operationId: mntnr_hardware.api_v1.logic.cabinet_update
      summary: updates cabinet
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the cabinet
        - name: cabinet
          in: body
          description: cabinet json
          schema:
            $ref: '#/definitions/CabinetUpdate'
      responses:
        200:
          description: updated cabinet
          schema:
            $ref: '#/definitions/Cabinet'

  /hardware/cabinet-assignments:
    get:
      operationId: mntnr_hardware.api_v1.logic.cabinet_assignments_list
      summary: lists cabinet assignments
      tags: ['hardware']
      responses:
        200:
          description: cabinet assignment list
          schema:
            $ref: '#/definitions/CabinetAssignmentList'
    post:
      operationId: mntnr_hardware.api_v1.logic.cabinet_assignment_create
      summary: assigns a device to a cabinet
      tags: ['hardware']
      parameters:
        - name: assignment
          in: body
          description: the cabinet assignment object to create
          schema:
            $ref: '#/definitions/CabinetAssignmentUpdate'
      responses:
        201:
          description: cabinet assignment
          schema:
            $ref: '#/definitions/CabinetAssignment'

  /hardware/cabinet-assignments/{id}:
    get:
      operationId: mntnr_hardware.api_v1.logic.cabinet_assignment_detail
      summary: shows details of cabinet assignment
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the assignment
      responses:
        200:
          description: cabinet assignment
          schema:
            $ref: '#/definitions/CabinetAssignment'
    delete:
      operationId: mntnr_hardware.api_v1.logic.cabinet_assignment_delete
      summary: deletes cabinet assignment
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of assignment to delete
      responses:
        200:
          description: deleted
    put:
      operationId: mntnr_hardware.api_v1.logic.cabinet_assignment_update
      summary: updates cabinet assignment
      tags: ['hardware']
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: UUID of the assignment
        - name: assignment
          in: body
          description: assignment json
          schema:
            $ref: '#/definitions/CabinetAssignmentUpdate'
      responses:
        200:
          description: updated
          schema:
            $ref: '#/definitions/CabinetAssignment'

definitions:
  DatacenterUpdate:
    type: object
    properties:
      name:
        type: string
        example: soma
      vendor:
        type: string
        example: hosting.com
      address:
        type: string
        description: where cabinets are
        example: 630 3rd St, San Francisco CA
      noc_phone:
        type: string
        example: 14155551212
      noc_email:
        type: string
        format: email
        example: noc@hosting.com
      noc_url:
        type: string
        format: url
        example: https://hosting.com
  Datacenter:
    required:
      - name
      - vendor
      - address
      - noc_phone
    allOf:
      - $ref: '#/definitions/DatacenterUpdate'
    properties:
      id:
        type: string
        format: uuid
        example: 95833eff-0e68-4137-95a9-23a40cca3b11
  DatacenterEmbedded:
    type: object
    required: ['id']
    properties:
      id:
        type: string
        format: uuid
        description: UUID of the datacenter object
        example: 3bdd8e5b-3ffb-4053-96fc-3d5fb73b88f9
      name:
        type: string
        description: datacenter name
        example: Layer42
        readOnly: true
  DatacenterList:
    type: array
    items:
      $ref: '#/definitions/Datacenter'
  CabinetUpdate:
    type: object
    properties:
      name:
        type: string
        example: 'c23-r55-l7'
      datacenter:
        $ref: '#/definitions/DatacenterEmbedded'
      rack_units:
        type: integer
        example: 42
      depth:
        type: number
        description: inches from front rack post to rear rack post
        example: 41.34
      width:
        type: number
        description: inches from left rack post to right rack post
        example: 19
      attachment:
        type: string
        format: cabinet_attachment_enum
        description: CAGE_NUT_95, DIRECT_ATTACH, or OTHER
        example: CAGE_NUT_95
      fasteners:
        type: string
        format: cabinet_fastener_enum
        description: UNF_10_32, UNC_12_24, M5, M6 or OTHER
        example: UNF_10_32
  Cabinet:
    required:
      - name
      - datacenter
      - rack_units
      - depth
      - width
      - attachment
      - fasteners
    allOf:
      - $ref: '#/definitions/CabinetUpdate'
    properties:
      id:
        type: string
        format: uuid
        example: c6ab6f4b-87f8-454f-b781-e8a33e032be6
  CabinetDetail:
    allOf:
      - $ref: '#/definitions/Cabinet'
    properties:
      power:
        type: integer
        description: total power (watts) provided by assigned PDUs
        example: 6240
        readOnly: true
      power_allocated:
        type: integer
        description: power (watts) allocated to devices in cabinet
        example: 405
        readOnly: true
      power_available:
        type: integer
        description: power (watts) not yet allocated
        example: 5835
        readOnly: true
  CabinetList:
    type: array
    items:
      $ref: '#/definitions/Cabinet'
  CabinetAssignment:
    type: object
    allOf:
      - $ref: '#/definitions/CabinetAssignmentUpdate'
    properties:
      id:
        type: string
        format: uuid
        description: assignment uuid
        example: fa069c96-1b73-42e5-80f1-32bdfaffec70
  CabinetAssignmentList:
    type: array
    items:
      $ref: '#/definitions/CabinetAssignment'
  CabinetAssignmentCreate:
    type: object
    required:
      - cabinet
      - device
      - depth
      - orientation
      - position
    allOf:
      - $ref: '#/definitions/CabinetAssignmentUpdate'
  CabinetAssignmentUpdate:
    type: object
    properties:
      cabinet:
        type: object
        required: ['id']
        properties:
          id:
            type: string
            format: uuid
            description: cabinet id
            example: c19c2653-7858-4701-bb44-899efccb7043
      device:
        type: object
        required: ['id']
        properties:
          id:
            type: string
            format: uuid
            description: device id
            example: 8c40096e-60a7-46e8-a679-a09aec9295f8
      depth:
        type: string
        format: device_depth_enum
        description: HALF or FULL
        example: HALF
      orientation:
        type: string
        format: device_orientation_enum
        description: FRONT or REAR
        example: FRONT
      position:
        type: integer
        description: which rack slot the device starts in
        example: 1